FROM node:20-bullseye AS builder

WORKDIR /build

COPY ./package*.json .

RUN npm install

ARG SET_NODE_ENV=production
ARG SET_DOMAIN_NAME=yunho.dev
ARG SET_EMAIL=e3d305ca3dd159da2aeb67c8994cea36

ENV NODE_ENV=${SET_NODE_ENV}
ENV DOMAIN_NAME=${SET_DOMAIN_NAME}
ENV EMAIL=${SET_EMAIL}

COPY . .

RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /build/.next/standalone .
COPY --from=builder /build/.next/static ./.next/static
COPY public ./public

RUN addgroup --system nodejs && \
  adduser --system --ingroup nodejs nextjs && \
  chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 3000

CMD ["node", "server.js"]