FROM node:20-bullseye

ENV TZ=Asia/Seoul
ENV EMAIL=e3d305ca3dd159da2aeb67c8994cea36

WORKDIR /app

COPY package*.json .

COPY . .

RUN npm install

ENV NODE_ENV=development

CMD ["npm", "run", "dev"]
