services:
  client:
    image: ${GHCR_IMAGE_URL}/client:latest
    container_name: client
    networks:
      - proxy
    environment:
      - NODE_ENV=production
      - DOMAIN_NAME=${DOMAIN_NAME}
      - NEXT_PUBLIC_GENIUS_API_KEY=${NEXT_PUBLIC_GENIUS_API_KEY}
      - NEXT_PUBLIC_VAPID_PUBLIC_KEY=${NEXT_PUBLIC_VAPID_PUBLIC_KEY}

  api:
    image: ${GHCR_IMAGE_URL}/api:latest
    container_name: api
    networks:
      - proxy
      - cache
      - db
    environment:
      - DEPLOY_MODE=production
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - PGPORT=${PGPORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}
      - WEBPUSH_SUBJECT=${WEBPUSH_SUBJECT}

  analysis:
    image: ${GHCR_IMAGE_URL}/analysis:latest
    container_name: analysis
    networks:
      - cache
      - db
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - PGPORT=${PGPORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - ./analysis/prompt_template:/app/prompt_template
  
  cache:
    image: ${GHCR_IMAGE_URL}/cache:latest
    container_name: cache
    networks:
      - cache

  db:
    image: ${GHCR_IMAGE_URL}/db:latest
    container_name: db
    networks:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

  proxy:
    image: ${GHCR_IMAGE_URL}/proxy:latest
    container_name: proxy
    ports:
      - 80:80
      - 443:443 
    networks:
      - proxy
    volumes:
      - certbot_letsencrypt:/etc/letsencrypt
      - certbot_www:/var/www/certbot

networks:
  proxy:
    external: true
  db:
    driver: bridge
  cache:
    driver: bridge

volumes:
  db_data:
    external: true
  certbot_letsencrypt:
    external: true
  certbot_www:
    external: true
