services:
  client:
    image: ${GHCR_IMAGE_URL}/client:latest
    ports:
      - 3112:3000
    networks:
      - proxy

  api:
    image: ${GHCR_IMAGE_URL}/api:latest
    ports:
      - 8008:8000
    networks:
      - proxy
      - db

  db:
    image: ${GHCR_IMAGE_URL}/db:latest
    ports:
      - 5488:5432
    networks:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - db_data:/bitnami/postgresql

  proxy:
    image: ${GHCR_IMAGE_URL}/proxy:latest
    ports:
      - 80:80
      - 443:443 
    networks:
      - proxy
    volumes:
      - ./certbot/etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/var/log/letsencrypt:/var/log/letsencrypt

networks:
  proxy:
    driver: bridge
  db:
    driver: bridge

volumes:
  db_data:
    external: true