FROM python:3.12-alpine

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

RUN addgroup -S python && \
  adduser -S fastapi && \
  chown -R fastapi:python /app

USER fastapi

EXPOSE 8000

CMD ["python", "run.py"]