name: API Image Build and Push

on:
  push:
    branches:
      - main
    paths:
      - api/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push
        uses: ./.github/actions/docker-build
        with:
          context: api
          image_name: api
          REGISTRY_VARIABLE: ${{ secrets.REGISTRY_VARIABLE }}
          CHCR_PAT: ${{ secrets.CHCR_PAT }}
