name: Cache Image Build and Push

on:
  push:
    branches:
      - main
    paths:
      - cache/**
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      context: cache
      image_name: cache
    secrets:
      REGISTRY_VARIABLE: ${{ secrets.REGISTRY_VARIABLE }}
      CHCR_PAT: ${{ secrets.CHCR_PAT }}
