name: Client Image Build and Push

on:
  push:
    branches:
      - main
    paths:
      - client/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push
        uses: ./.github/workflows/reusable-docker-build.yml
        with:
          context: client
          image_name: client
          REGISTRY_VARIABLE: ${{ secrets.REGISTRY_VARIABLE }}
          CHCR_PAT: ${{ secrets.CHCR_PAT }}
