name: Client Image Build and Push

on:
  push:
    branches:
      - main
    paths:
      - client/**

jobs:
  build:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      context: client
      image_name: client
    secrets:
      REGISTRY_VARIABLE: ${{ secrets.REGISTRY_VARIABLE }}
      CHCR_PAT: ${{ secrets.CHCR_PAT }}
