name: DB Image Build and Push

on:
  push:
    branches:
      - main
    paths:
      - db/**

jobs:
  build:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      context: db
      image_name: db
    secrets:
      REGISTRY_VARIABLE: ${{ secrets.REGISTRY_VARIABLE }}
      CHCR_PAT: ${{ secrets.CHCR_PAT }}
