name: Proxy Image Build and Push

on:
  push:
    branches:
      - main
    paths:
      - proxy/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push
        uses: ./.github/actions/docker-build/build-push.yml
        with:
          context: proxy
          image_name: proxy
          REGISTRY_VARIABLE: ${{ secrets.REGISTRY_VARIABLE }}
          CHCR_PAT: ${{ secrets.CHCR_PAT }}
