name: Proxy Image Build and Push

on:
  push:
    branches:
      - main
    paths:
      - proxy/**

jobs:
  build:
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      context: proxy
      image_name: proxy
    secrets:
      REGISTRY_VARIABLE: ${{ secrets.REGISTRY_VARIABLE }}
      CHCR_PAT: ${{ secrets.CHCR_PAT }}
