name: Reusable Docker Build

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      image_name:
        required: true
        type: string
      build_args:
        required: false
        type: object
    secrets:
      REGISTRY_VARIABLE:
        required: true
      CHCR_PAT:
        required: true

permissions:
  contents: write
  packages: write

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.CHCR_PAT }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          build_args: ${{ toJSON(inputs.build_args) }}
          tags: ghcr.io/${{ secrets.REGISTRY_VARIABLE }}/${{ inputs.image_name }}:latest
          platforms: linux/amd64,linux/arm64
          push: true
