name: Reusable Docker Build

on:
  workflow_call:
    inputs:
      context:
        required: true
        type: string
      image_name:
        required: true
        type: string
    secrets:
      REGISTRY_VARIABLE:
        required: true
      CHCR_PAT:
        required: true

permissions:
  contents: write
  packages: write

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor}}
          password: ${{ secrets.CHCR_PAT }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ${{ inputs.context }}
          push: true
          tags: ghcr.io/${{ secrets.REGISTRY_VARIABLE }}/${{ inputs.image_name }}:latest
